### ISSUE TITLE
[Suggestion] Rename the package FieldDefaultValues.jl

### ISSUE THREAD

**Issue by briochemc** [rafaqz/Defaults.jl#1]
I thought this would make it clearer as to what it does (Defaults.jl sounds very general) and fit with your new FieldMetadata.jl package name.

(ps: I was out for a couple weeks but will try your suggestions soon...)

**Comment by rafaqz** [comment]
Maybe FieldDefaults.jl is clearest? I can put it in METADATA too now that FieldMetatdata is registered.

**Comment by briochemc** [comment]
I just meant it as a suggestion — you do what you want with it 😄 And yes I think you are right, FieldDefaults is shorter and still just as clear IMHO.

Also +1 for putting it in METADATA!

**Comment by briochemc** [comment]
Just wondering: Is there something stopping you from renaming and putting into METADATA?

**Comment by rafaqz** [comment]
I'm too busy and its low prority! It also means updating a few of my other
packages. If you want to put in a pull request with the name change to
FieldDefaults that would speed it up a lot.

Make sure to get all the CI for Travis and appveyor.

**Comment by briochemc** [comment]
Oh I see ! No worries then. (I thought it was a quick thing to do.) I have never done that myself so I may give it a try but there is no guarantee :)
